import { jsPDF } from "jspdf";

const SECTION_LABELS = {
  glucose: "Glucose Patterns",
  meal:    "Meal Correlations",
  symptom: "Symptom Patterns",
};

function confidenceLabel(dataPoints) {
  if (dataPoints < 5)  return "Low confidence";
  if (dataPoints < 15) return "Medium confidence";
  return "High confidence";
}

/**
 * Generates a plain-language PDF summary of detected patterns for a child,
 * formatted for sharing with an endocrinologist or care team, and triggers a download.
 */
export function exportPatternReport(child, patterns, lastUpdated) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth  = doc.internal.pageSize.getWidth();
  const margin     = 48;
  const maxWidth   = pageWidth - margin * 2;
  let y = margin;

  const ensureSpace = (needed) => {
    if (y + needed > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("GlycoGuard Pattern Summary", margin, y);
  y += 26;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(`Patient: ${child?.name || "—"}`, margin, y);
  y += 16;
  if (child?.dob) {
    doc.text(`Date of birth: ${child.dob}`, margin, y);
    y += 16;
  }
  doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y);
  y += 16;
  if (lastUpdated) {
    doc.text(`Analysis last updated: ${lastUpdated.toLocaleString()}`, margin, y);
    y += 16;
  }
  doc.text("Window: most recent 30 days of logged data", margin, y);
  y += 28;

  const grouped = patterns.reduce((acc, p) => {
    (acc[p.category] = acc[p.category] || []).push(p);
    return acc;
  }, {});

  for (const [key, label] of Object.entries(SECTION_LABELS)) {
    const items = grouped[key] || [];
    if (!items.length) continue;

    ensureSpace(28);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(label, margin, y);
    y += 20;

    for (const p of items) {
      const titleLines = doc.splitTextToSize(p.title, maxWidth);
      const descLines  = doc.splitTextToSize(p.description, maxWidth);
      const metaLine   = `${confidenceLabel(p.dataPoints)} · ${p.dataPoints} data points`;

      ensureSpace(titleLines.length * 14 + descLines.length * 13 + 28);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.text(titleLines, margin, y);
      y += titleLines.length * 14;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(descLines, margin, y);
      y += descLines.length * 13;

      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(120);
      doc.text(metaLine, margin, y);
      doc.setTextColor(0);
      y += 22;
    }
    y += 8;
  }

  ensureSpace(40);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(120);
  const disclaimer = doc.splitTextToSize(
    "This report is generated by GlycoGuard's pattern recognition engine from parent-logged data. " +
    "It is intended to support — not replace — clinical judgement.",
    maxWidth
  );
  doc.text(disclaimer, margin, y);

  const datestamp = new Date().toISOString().slice(0, 10);
  const namePart  = (child?.name || "patient").replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  doc.save(`glycoguard-pattern-report-${namePart}-${datestamp}.pdf`);
}
